/*
Copyright (c) 2012, Percy Wegmann
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
*/

/*
 * This file defines compound expression and compound extractable expressions based on tuples.
 * These are auto-generated from this
 * <a href="https://docs.google.com/spreadsheet/ccc?key=0AthXvKF2QyamdEFVdDFGMzBVYmxGempheEpHOU9WZkE#gid=0">google spreadsheet</a>. 
 */
package org.sqins

import java.sql.ResultSet

case class CompoundExpression2[T1 <: Expression, T2 <: Expression](override val _1: T1, override val _2: T2) extends Tuple2(_1, _2) with Expression {
  override def expression = "%1$s, %2$s".format(_1.expression, _2.expression)
  override def selectExpression = "%1$s, %2$s".format(_1.selectExpression, _2.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues
}
case class CompoundExpression3[T1 <: Expression, T2 <: Expression, T3 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3) extends Tuple3(_1, _2, _3) with Expression {
  override def expression = "%1$s, %2$s, %3$s".format(_1.expression, _2.expression, _3.expression)
  override def selectExpression = "%1$s, %2$s, %3$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues
}
case class CompoundExpression4[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4) extends Tuple4(_1, _2, _3, _4) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s".format(_1.expression, _2.expression, _3.expression, _4.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues
}
case class CompoundExpression5[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5) extends Tuple5(_1, _2, _3, _4, _5) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues
}
case class CompoundExpression6[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6) extends Tuple6(_1, _2, _3, _4, _5, _6) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues
}
case class CompoundExpression7[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7) extends Tuple7(_1, _2, _3, _4, _5, _6, _7) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues
}
case class CompoundExpression8[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8) extends Tuple8(_1, _2, _3, _4, _5, _6, _7, _8) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues
}
case class CompoundExpression9[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9) extends Tuple9(_1, _2, _3, _4, _5, _6, _7, _8, _9) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues
}
case class CompoundExpression10[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10) extends Tuple10(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues
}
case class CompoundExpression11[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11) extends Tuple11(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues
}
case class CompoundExpression12[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12) extends Tuple12(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues
}
case class CompoundExpression13[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13) extends Tuple13(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues
}
case class CompoundExpression14[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14) extends Tuple14(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues
}
case class CompoundExpression15[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15) extends Tuple15(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues
}
case class CompoundExpression16[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16) extends Tuple16(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues
}
case class CompoundExpression17[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression, T17 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16, override val _17: T17) extends Tuple17(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression, _17.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression, _17.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues ++ _17.boundValues
}
case class CompoundExpression18[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression, T17 <: Expression, T18 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16, override val _17: T17, override val _18: T18) extends Tuple18(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression, _17.expression, _18.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression, _17.selectExpression, _18.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues ++ _17.boundValues ++ _18.boundValues
}
case class CompoundExpression19[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression, T17 <: Expression, T18 <: Expression, T19 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16, override val _17: T17, override val _18: T18, override val _19: T19) extends Tuple19(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression, _17.expression, _18.expression, _19.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression, _17.selectExpression, _18.selectExpression, _19.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues ++ _17.boundValues ++ _18.boundValues ++ _19.boundValues
}
case class CompoundExpression20[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression, T17 <: Expression, T18 <: Expression, T19 <: Expression, T20 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16, override val _17: T17, override val _18: T18, override val _19: T19, override val _20: T20) extends Tuple20(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s, %20$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression, _17.expression, _18.expression, _19.expression, _20.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s, %20$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression, _17.selectExpression, _18.selectExpression, _19.selectExpression, _20.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues ++ _17.boundValues ++ _18.boundValues ++ _19.boundValues ++ _20.boundValues
}
case class CompoundExpression21[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression, T17 <: Expression, T18 <: Expression, T19 <: Expression, T20 <: Expression, T21 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16, override val _17: T17, override val _18: T18, override val _19: T19, override val _20: T20, override val _21: T21) extends Tuple21(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s, %20$s, %21$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression, _17.expression, _18.expression, _19.expression, _20.expression, _21.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s, %20$s, %21$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression, _17.selectExpression, _18.selectExpression, _19.selectExpression, _20.selectExpression, _21.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues ++ _17.boundValues ++ _18.boundValues ++ _19.boundValues ++ _20.boundValues ++ _21.boundValues
}
case class CompoundExpression22[T1 <: Expression, T2 <: Expression, T3 <: Expression, T4 <: Expression, T5 <: Expression, T6 <: Expression, T7 <: Expression, T8 <: Expression, T9 <: Expression, T10 <: Expression, T11 <: Expression, T12 <: Expression, T13 <: Expression, T14 <: Expression, T15 <: Expression, T16 <: Expression, T17 <: Expression, T18 <: Expression, T19 <: Expression, T20 <: Expression, T21 <: Expression, T22 <: Expression](override val _1: T1, override val _2: T2, override val _3: T3, override val _4: T4, override val _5: T5, override val _6: T6, override val _7: T7, override val _8: T8, override val _9: T9, override val _10: T10, override val _11: T11, override val _12: T12, override val _13: T13, override val _14: T14, override val _15: T15, override val _16: T16, override val _17: T17, override val _18: T18, override val _19: T19, override val _20: T20, override val _21: T21, override val _22: T22) extends Tuple22(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22) with Expression {
  override def expression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s, %20$s, %21$s, %22$s".format(_1.expression, _2.expression, _3.expression, _4.expression, _5.expression, _6.expression, _7.expression, _8.expression, _9.expression, _10.expression, _11.expression, _12.expression, _13.expression, _14.expression, _15.expression, _16.expression, _17.expression, _18.expression, _19.expression, _20.expression, _21.expression, _22.expression)
  override def selectExpression = "%1$s, %2$s, %3$s, %4$s, %5$s, %6$s, %7$s, %8$s, %9$s, %10$s, %11$s, %12$s, %13$s, %14$s, %15$s, %16$s, %17$s, %18$s, %19$s, %20$s, %21$s, %22$s".format(_1.selectExpression, _2.selectExpression, _3.selectExpression, _4.selectExpression, _5.selectExpression, _6.selectExpression, _7.selectExpression, _8.selectExpression, _9.selectExpression, _10.selectExpression, _11.selectExpression, _12.selectExpression, _13.selectExpression, _14.selectExpression, _15.selectExpression, _16.selectExpression, _17.selectExpression, _18.selectExpression, _19.selectExpression, _20.selectExpression, _21.selectExpression, _22.selectExpression)
  override def boundValues = _1.boundValues ++ _2.boundValues ++ _3.boundValues ++ _4.boundValues ++ _5.boundValues ++ _6.boundValues ++ _7.boundValues ++ _8.boundValues ++ _9.boundValues ++ _10.boundValues ++ _11.boundValues ++ _12.boundValues ++ _13.boundValues ++ _14.boundValues ++ _15.boundValues ++ _16.boundValues ++ _17.boundValues ++ _18.boundValues ++ _19.boundValues ++ _20.boundValues ++ _21.boundValues ++ _22.boundValues
}

case class CompoundExtractableExpression2[T1, T2](override val _1: Extractable[T1], override val _2: Extractable[T2]) extends CompoundExpression2(_1, _2) with Extractable[Tuple2[T1, T2]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position)), columnsRead)
}
case class CompoundExtractableExpression3[T1, T2, T3](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3]) extends CompoundExpression3(_1, _2, _3) with Extractable[Tuple3[T1, T2, T3]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position)), columnsRead)
}
case class CompoundExtractableExpression4[T1, T2, T3, T4](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4]) extends CompoundExpression4(_1, _2, _3, _4) with Extractable[Tuple4[T1, T2, T3, T4]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position)), columnsRead)
}
case class CompoundExtractableExpression5[T1, T2, T3, T4, T5](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5]) extends CompoundExpression5(_1, _2, _3, _4, _5) with Extractable[Tuple5[T1, T2, T3, T4, T5]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position)), columnsRead)
}
case class CompoundExtractableExpression6[T1, T2, T3, T4, T5, T6](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6]) extends CompoundExpression6(_1, _2, _3, _4, _5, _6) with Extractable[Tuple6[T1, T2, T3, T4, T5, T6]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position)), columnsRead)
}
case class CompoundExtractableExpression7[T1, T2, T3, T4, T5, T6, T7](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7]) extends CompoundExpression7(_1, _2, _3, _4, _5, _6, _7) with Extractable[Tuple7[T1, T2, T3, T4, T5, T6, T7]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position)), columnsRead)
}
case class CompoundExtractableExpression8[T1, T2, T3, T4, T5, T6, T7, T8](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8]) extends CompoundExpression8(_1, _2, _3, _4, _5, _6, _7, _8) with Extractable[Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position)), columnsRead)
}
case class CompoundExtractableExpression9[T1, T2, T3, T4, T5, T6, T7, T8, T9](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9]) extends CompoundExpression9(_1, _2, _3, _4, _5, _6, _7, _8, _9) with Extractable[Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position)), columnsRead)
}
case class CompoundExtractableExpression10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10]) extends CompoundExpression10(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10) with Extractable[Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position)), columnsRead)
}
case class CompoundExtractableExpression11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11]) extends CompoundExpression11(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11) with Extractable[Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position)), columnsRead)
}
case class CompoundExtractableExpression12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12]) extends CompoundExpression12(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12) with Extractable[Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position)), columnsRead)
}
case class CompoundExtractableExpression13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13]) extends CompoundExpression13(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13) with Extractable[Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position)), columnsRead)
}
case class CompoundExtractableExpression14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14]) extends CompoundExpression14(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14) with Extractable[Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position)), columnsRead)
}
case class CompoundExtractableExpression15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15]) extends CompoundExpression15(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15) with Extractable[Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position)), columnsRead)
}
case class CompoundExtractableExpression16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16]) extends CompoundExpression16(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16) with Extractable[Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position)), columnsRead)
}
case class CompoundExtractableExpression17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16], override val _17: Extractable[T17]) extends CompoundExpression17(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17) with Extractable[Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position), doExtract(_17, rs, position)), columnsRead)
}
case class CompoundExtractableExpression18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16], override val _17: Extractable[T17], override val _18: Extractable[T18]) extends CompoundExpression18(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18) with Extractable[Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position), doExtract(_17, rs, position), doExtract(_18, rs, position)), columnsRead)
}
case class CompoundExtractableExpression19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16], override val _17: Extractable[T17], override val _18: Extractable[T18], override val _19: Extractable[T19]) extends CompoundExpression19(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19) with Extractable[Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position), doExtract(_17, rs, position), doExtract(_18, rs, position), doExtract(_19, rs, position)), columnsRead)
}
case class CompoundExtractableExpression20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16], override val _17: Extractable[T17], override val _18: Extractable[T18], override val _19: Extractable[T19], override val _20: Extractable[T20]) extends CompoundExpression20(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20) with Extractable[Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position), doExtract(_17, rs, position), doExtract(_18, rs, position), doExtract(_19, rs, position), doExtract(_20, rs, position)), columnsRead)
}
case class CompoundExtractableExpression21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16], override val _17: Extractable[T17], override val _18: Extractable[T18], override val _19: Extractable[T19], override val _20: Extractable[T20], override val _21: Extractable[T21]) extends CompoundExpression21(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21) with Extractable[Tuple21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position), doExtract(_17, rs, position), doExtract(_18, rs, position), doExtract(_19, rs, position), doExtract(_20, rs, position), doExtract(_21, rs, position)), columnsRead)
}
case class CompoundExtractableExpression22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](override val _1: Extractable[T1], override val _2: Extractable[T2], override val _3: Extractable[T3], override val _4: Extractable[T4], override val _5: Extractable[T5], override val _6: Extractable[T6], override val _7: Extractable[T7], override val _8: Extractable[T8], override val _9: Extractable[T9], override val _10: Extractable[T10], override val _11: Extractable[T11], override val _12: Extractable[T12], override val _13: Extractable[T13], override val _14: Extractable[T14], override val _15: Extractable[T15], override val _16: Extractable[T16], override val _17: Extractable[T17], override val _18: Extractable[T18], override val _19: Extractable[T19], override val _20: Extractable[T20], override val _21: Extractable[T21], override val _22: Extractable[T22]) extends CompoundExpression22(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22) with Extractable[Tuple22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22]] with CompoundExtractable {
  override def extract(rs: ResultSet, position: Int) = Extraction((doExtract(_1, rs, position), doExtract(_2, rs, position), doExtract(_3, rs, position), doExtract(_4, rs, position), doExtract(_5, rs, position), doExtract(_6, rs, position), doExtract(_7, rs, position), doExtract(_8, rs, position), doExtract(_9, rs, position), doExtract(_10, rs, position), doExtract(_11, rs, position), doExtract(_12, rs, position), doExtract(_13, rs, position), doExtract(_14, rs, position), doExtract(_15, rs, position), doExtract(_16, rs, position), doExtract(_17, rs, position), doExtract(_18, rs, position), doExtract(_19, rs, position), doExtract(_20, rs, position), doExtract(_21, rs, position), doExtract(_22, rs, position)), columnsRead)
}